{% set data = load_setup_py_data(from_recipe_dir=True) %}

package:
  name: {{data["name"]}}
  version: {{data["version"]}}

source:
  path: .

build:
  number: 0
  noarch: python
  script:
    - python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - networkx
    - numpy
    - six
    - rdkit
    - enum34 [py27]

    - setuptools
    - pyyaml

  run:
    - python
    - networkx
    - numpy
    - six
    - rdkit
    - enum34 [py27]
    - tqdm

test:
  imports:
    - mordred

  requires:
    - nose
    - pyyaml
    - coveralls

  commands:
    - nosetests mordred --with-coverage --cover-package=mordred
